import type { Metadata } from "next";
import "./globals.css";
import BottomNav from "./_components/navigation/BottomNav";
import Sidebar from "./_components/navigation/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="bg-black text-white antialiased">
        <div className="flex flex-col md:flex-row min-h-screen">
          <aside className="hidden md:flex w-64 fixed h-full border-r border-yellow-500 bg-black z-50">
            <Sidebar />
          </aside>

          <main className="flex-1 md:ml-64 min-h-screen relative">
            {children}
          </main>

          <div className="md:hidden">
            <BottomNav />
          </div>
        </div>
      </body>
    </html>
  );
}
